version: "3.8"

services:
  # Service pour l'application .NET
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=QuizzAppDb;User Id=sa;Password=DockerPasswordYg123;TrustServerCertificate=True;MultipleActiveResultSets=True;
    depends_on:
      - sqlserver
    networks:
      - quizz-network

  # Service pour SQL Server
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DockerPasswordYg123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - quizz-network

networks:
  quizz-network:
    driver: bridge

volumes:
  sqlserver-data:
